#!/bin/bash

while read test_suite; do
    type -p $test_suite 1>&2 || { echo "$0: test suite '$test_suite' not found" >&2; exit 1; }
    $test_suite >&2
    echo "$test_suite/status=$?"
done < <( grep -v "^#" | grep -v "^$" ) # quick and dirty
