#!/bin/bash

function test_iterator
{
    python3 -c "$( cat <<END
import sys
import snark.imaging
from comma.io import windows_binary
print("test_iterator loaded comma and snark", file=sys.stderr)
for i in snark.imaging.cv.iterator(): snark.imaging.cv.write(i)
print("test_iterator finished", file=sys.stderr)
END
)"
}

output=$( csv-to-bin t,3ui,6ub | test_iterator | csv-from-bin t,3ui,6ub )
status=$?
echo "test/iterator/output=\"$output\""
echo "test/iterator/status=$status"
