#!/bin/bash

#prerequisites: install google unit tests and set add install path to PATH
#(e.g. PATH=$PATH:/usr/local/share/test)

readonly output_dir=output
declare count=0
mkdir -p $output_dir

grep "^[^#]" | while read unit_test; do
    $unit_test >&2 \
        && echo "test[$count]/status=\"$unit_test:success\"" \
        || echo "test[$count]/status=\"$unit_test:failed\""
    (( count++ ))
done
