#!/usr/bin/env python3

from snark.ros import convert
import sys

for line in sys.stdin:
    test_name, type_str = line.strip().split("=")
    type_str = type_str.strip('"')
    for test_fn in ['is_binary_type', 'is_primitive_type']:
        print( f"{test_name}/{test_fn}={ '1' if getattr( convert, test_fn )( type_str ) else '0' }" )
