#!/usr/bin/env python3

from snark.ros2 import convert
import comma.csv
from rosidl_runtime_py.utilities import get_message
import sys

def remove_comments( lines ):
    for line in lines:
        stripped = line.split('#', 1)[0].rstrip()
        if stripped:
            yield stripped

for line in remove_comments( sys.stdin ):
    test_name, msg_full_path = line.split("=")
    msg_full_path = msg_full_path.strip('"')
    msg_class = get_message( msg_full_path )
    record_t, record_ctor = convert.ros_message_to_csv_record( msg_class() )
    # we only show the top-level fields, we don't walk down the tree
    for i, ( field_name, field_type ) in enumerate( zip( record_t.concise_fields, record_t.concise_types )):
        if isinstance( field_type, comma.csv._struct.struct ): field_type = "nested struct"
        print( f"{test_name}/fields/{i}/name=\"{field_name}\"" )
        print( f"{test_name}/fields/{i}/type=\"{field_type}\"" )
