#!/bin/bash

sudo cp frontend.json /var/www/html/feeds/config/frontend.examples.basic.json

#!/bin/bash

sudo cp frontend.json /var/www/html/feeds/config/snark.web.feeds.examples.basic.frontend.json
firefox http://localhost/feeds/?config=config/snark.web.feeds.examples.basic.frontend.json &
echo 0,80 > count.csv
snark-webframes --config=backend.json --port=7000 --timeout=15 --verbose