#!/bin/bash
name=$(basename $0)

function die() {
    echo -e "$name: $@" >&2
    exit 1
}

function usage() {
    cat >&2 <<eof
Builds a docker image that can in turn build a snark .DEB package.
If --vimba is provided, the Vimba SDK will be unpacked and installed
so that snark can be built with Vimba support.

usage: $name <ubuntu version> <comma_deb> [<snark dir>] [--vimba=<vimba_pkg>]

example:
    $name 20.04 comma-1.2.3-20.04.deb --vimba=Vimba_v4.2_Linux.tgz

eof
    exit 1
}

vimba_pkg=""
args=()
for arg in "$@"; do
    case "$arg" in
    --vimba=*) vimba_pkg="${arg#*=}" ;;
    *) args+=("$arg") ;;
    esac
done

version="${args[0]}"
comma_deb="${args[1]}"
snark_dir="${args[2]}"

[[ -n "$version" && -s "$comma_deb" ]] || usage
[[ -n "$snark_dir" ]] || snark_dir=$(realpath ~/src/snark)
[[ -d "$snark_dir" ]] || {
    echo "usage: $name please specify <snark dir> explicitly (since you seem to either run with sudo or have snark not in '$snark_dir')" >&2
    exit 1
}
[[ -z "$vimba_pkg" || -s "$vimba_pkg" ]] || die "vimba package '$vimba_pkg' not found or empty"

echo "$name: running:" >&2

extra_args=()
[[ -n "$vimba_pkg" ]] && extra_args=(--build-arg vimba_pkg=${vimba_pkg})
docker build -t ubuntu.$version.build.snark \
    --build-arg version=$version \
    --build-arg comma_deb=${comma_deb} \
    "${extra_args[@]}" \
    -f "$snark_dir/system/package/cpack/Dockerfile" .
