#!/bin/bash
name=$( basename $0 )
function die() { echo "$name: $@" >&2; exit 1; }
ubuntu_version=$1
snark_version=$2
snark_dir="$3"
[[ -n "$ubuntu_version" && -n "$snark_version" ]] || die "usage: <ubuntu version> <snark version> [<snark dir>]"
[[ -n "$snark_dir" ]] || snark_dir="$( realpath ~/src/snark )"
[[ -d "$snark_dir" ]] || die "usage: please specify <snark dir> explicitly (since you seem to either run with sudo or have snark not in '$snark_dir')"

docker run \
       --mount "type=bind,source=$snark_dir,target=/mnt/snark" \
       --mount "type=bind,source=$( pwd ),target=/root/output" \
       ubuntu.$ubuntu_version.build.snark \
       /mnt/snark/system/package/cpack/snark-package-make $ubuntu_version $snark_version /mnt/snark || die "failed"
