#!/bin/bash

# Copyright (c) 2019 The University of Sydney
# Copyright (c) 2020,2022 Mission Systems Pty Ltd

scriptname=$( basename $0 )

source $( type -p comma-application-util ) || { echo "$scriptname: cannot source comma-application-util" >&2; exit 1; }

function description()
{
    cat <<EOF
--help,-h;           show this help and exit
--verbose,-v;        show more information
--config=[<file>];   defaults to config.json:ouster
--device=[<lidar>];  host name of lidar
--output-fields;     show output fields and exit
--output-format;     show output format and exit
--packet-size;       show packet size and exit
--port=<port>;       default=7501; command port
--use-host-time;     apply system time from host to data
EOF
}

available_operations="command,config,init,lidar,imu,alerts,stream_alerts"
tested_firmware="1.12.0,1.13.0,2.3.1"
tested_firmware_re="^v($( tr , '|' <<< $tested_firmware ))$"

# Configurable parameters with possible values, defaults and units
# For multiple option settings put the default option first
declare -A configurable_parameters
configurable_parameters=(
    ["timestamp_mode"]="TIME_FROM_INTERNAL_OSC,TIME_FROM_PPS_IN_SYNCED,TIME_FROM_PTP_1588"
    ["lidar_mode"]="512x10,1024x10,2048x10,512x20,1024x20"
    ["multipurpose_io_mode"]="OFF,INPUT_NMEA_UART,OUTPUT_FROM_INTERNAL_OSC,OUTPUT_FROM_SYNC_PULSE_IN,OUTPUT_FROM_PTP_1588,OUTPUT_FROM_ENCODER_ANGLE"
    ["sync_pulse_out_polarity"]="ACTIVE_LOW,ACTIVE_HIGH"
    ["sync_pulse_out_frequency"]="1 Hz"
    ["sync_pulse_out_angle"]="360 deg"
    ["sync_pulse_out_pulse_width"]="10 ms"
)

function text_wrap()
{
    local prefix=$1
    local text
    while IFS= read text; do
        local head=$( sed "s/$prefix.*/$prefix/" <<< "$text" )
        local tail=$( sed "s/$head//" <<< "$text" )
        echo -n "$head"
        if [[ $tail ]]; then
            tail=$( sed 's/,/*,/' <<< $tail )
            local head_width=${#head}
            local tail_width=$(( 80 - head_width ))
            local spacer=$( printf ' %.0s' $( seq 1 $head_width ) )
            echo "$tail" | fold -s -w$tail_width | sed "2,\$s/^/$spacer/"
        else
            echo ""
        fi
    done
}

function usage()
{
    cat <<EOF >&2

get data from the Ouster OS-1 lidar

usage: $scriptname <operation> [<options>]

    where <operation> is one of:
        command        - reads commands from stdin
        config         - outputs the sensor configuration for --device
        init           - initializes the device with the address of the host
        lidar          - streams lidar data
        imu            - streams imu data
        alerts         - current snapshot of alerts
        stream_alerts  - continuous stream of alerts

    if required "lidar" and "imu" will perform an "init" first

options:
EOF
    description | sed 's/^/    /g' >&2
        cat <<EOF >&2

    some options are relevant only to certain operations:

    config:  --device
    imu:     --output-fields, --output-format
    lidar:   --output-fields, --output-format

    command port is taken from the config file, but can be overridden by
    the --port option. If neither is specified it defaults to 7501

EOF
    if (( options_verbose )); then
        cat <<EOF >&2
configuration:
    the normal process of configuration is to run:

        $scriptname config --device <lidar-addr> > config.json

    to generate a config file, then edit that file to make required changes,
    including adding the following:

    "address": <ip or host name of destination>,
    "port": <publishing port>,
    "binary": <format>,
    "device": { "host": <host name of lidar>, "target": <target ip for data> },

    You can optionally add "bandwidth_monitor_port" within the "lidar" and
    "imu" sections to publish the raw bandwidth.

    Once this config file has been created it can be updated with:

        $scriptname config --config config.json | sponge config.json

    which will preserve the address, port and device parameters.

parameters:
    configurable parameters are:

EOF
        for configurable_parameter in "${!configurable_parameters[@]}"; do
            (
                echo -n "    $configurable_parameter: "
                value=${configurable_parameters[$configurable_parameter]}
                if [[ $value =~ , ]]; then
                    echo "one of $( sed 's/,/, /g' <<< $value )"
                else
                    IFS=" " read default units <<< $value
                    echo "$units (default $default)"
                fi
            )
        done | sort | text_wrap "one of "
        cat <<EOF >&2

    * = default

    if you change any configurable parameter it should be loaded with

        $scriptname init --config <file>

examples:

    --- commands ---
    echo get_sensor_info | $scriptname command
    echo get_alerts | $scriptname command
    echo "get_config_param active timestamp_mode" | $scriptname command
    echo "set_config_param lidar_mode 1024x10" | $scriptname command
    echo reinitialize | $scriptname command

    Note that values are sticky across calls to reinitialize. Only a
    power-cycle resets them to defaults.

    Any parameters that can be set via the config file (see above) should be
    done that way, followed by "$scriptname init --config <file>"

    --- data acquisition ---
    $scriptname config --device os1-991832000987.local
    $scriptname init
    $scriptname lidar
    $scriptname imu

    --- logging ---
    block_size=\$(( \$( $scriptname lidar --output-format | csv-format size ) * 16 ))
    $scriptname lidar | csv-split --size \$block_size --period 60

    block_size=\$( $scriptname imu --output-format | csv-format size )
    $scriptname imu | csv-split --size \$imu_block_size  --period 60

    --- alerts ---
    $scriptname alerts
    $scriptname stream_alerts

EOF
    else
        cat <<EOF >&2
For more detailed help, including examples, add the --verbose flag.

see also:
    ouster-to-csv

EOF
    fi
    exit 0
}

function say() { echo "$scriptname: $@" >&2; }
function verbose() { (( options_verbose )) && say "$@"; }
function die() { say "$@"; exit 1; }

if (( $( comma_options_has "--bash-completion" $@ ) )); then
    description | comma_options_to_bash_completion
    echo $available_operations | tr ',' '\n'
    exit 0
fi

if (( $( comma_options_has "--help" $@ ) || $( comma_options_has "-h" $@ ) )); then
    options_verbose=$(( $( comma_options_has "--verbose" $@ ) || $( comma_options_has "-v" $@ ) ))
    usage
fi

options="$( description | comma-options-to-name-value "$@" )"
comma_path_value_to_var --prefix=options < <( echo "$options" | grep '=' )

unnamed_options=( $( echo "$options" | grep -v '=' | sed 's/^"//g; s/"$//g' | tr '\n' ' ' ) )

function prefix { csv-fields prefix --path $1; }

# file path      -> file:path
# file:path path -> file:path/path
function config_path_concat()
{
    echo $1:$2 | sed 's!:!/!2'
}

function load_config()
{
    local config_file=$1
    if [[ $config_file ]]; then
        local file path
        IFS=: read file path <<< "$config_file"
        [[ -e $file ]] || die "couldn't find config file \"$file\""
        cat "$file" | name-value-get "$path" | tr '[]' '__'
    fi
}

operation=${unnamed_options[0]}

if [[ $operation == "config" ]]; then
    [[ $options_config ]] || [[ $options_device ]] || die "one of --config or --device is required"
fi

if [[ $options_config ]]; then
    # use device/host as a sanity check
    device_name=$( load_config $( config_path_concat $options_config device/host ) )
    [[ $device_name ]] || die "failed to load config $options_config"
    verbose "loading config for $device_name"
    comma_path_value_to_var --prefix=parameter < <( load_config $( config_path_concat $options_config parameters ) )
    comma_path_value_to_var --prefix=lidar_data_format < <( load_config $( config_path_concat $options_config lidar_data_format ) )
    lidar=$( load_config $( config_path_concat $options_config device/host ) )
fi

# default to api v1 values
lidar_pixels_per_column=${lidar_data_format_pixels_per_column:-64}
lidar_azimuth_blocks_per_packet=${lidar_data_format_azimuth_blocks_per_packet:-16}

if [[ $lidar_data_format_udp_profile_lidar ]]; then
    [[ $lidar_data_format_udp_profile_lidar == "LEGACY" ]] || die "only LEGACY format supported for v2 api"
fi

function output_fields()
{
    case $1 in
        lidar)
            local channel_fields=$( seq -w 0 $(( lidar_pixels_per_column - 1 )) | sed 's/^/channel_/' | while read line; do seq 0 2 | sed "s/^/${line}_data_/"; done | tr '\n' , | sed 's/,$//' )
            echo "timestamp,measurement_id,frame_id,encoder_count,$channel_fields,packet_status"
            ;;
        imu)
            echo $( echo start,acceleration,gyro | prefix time ),$( echo x,y,z | prefix acceleration ),$( echo -n x,y,z | prefix angular_acceleration )
            ;;
        alerts|stream_alerts)
            echo "t,cursor,code,brief,description"
            ;;
        *) die "invalid operation: $1"
    esac
}

function output_format()
{
    case $1 in
        lidar) echo "ul,2uw,ui,$(( 3 * lidar_pixels_per_column ))ui,ui" ;;
        imu)   echo "3ul,3ui,3ui" ;;
        alerts|stream_alerts) echo "t,ul,s[128],s[128],s[256]" ;;
        *) die "invalid operation: $1"
    esac
}

# Get the lidar data format from config, or otherwise assume it's v1 format
# See Firware User Manual v2.3.1 §6.2.2 for v2 legacy sizes
function packet_size()
{
    case $1 in
        lidar) echo $(( $lidar_azimuth_blocks_per_packet * $( output_format lidar | csv-format size ) )) ;;
        imu)   output_format imu | csv-format size ;;
        *)     die "invalid operation for packet_size: $1"
    esac
}

(( $( comma_options_has --output-fields "$@" ) )) && { output_fields $operation; exit 0; }
(( $( comma_options_has --output-format "$@" ) )) && { output_format $operation; exit 0; }
(( $( comma_options_has --packet-size "$@" ) )) && { packet_size $operation; exit 0; }

[[ $options_device ]] && lidar=$options_device
[[ $lidar ]] || die "lidar host name or ip address is required"

if (( ! $( comma_options_has --port $@ ) )) && [[ $parameter_tcp_port ]]; then
    command_port=$parameter_tcp_port
else
    command_port=$options_port
fi
verbose "connecting to $lidar on command port $command_port"

if [[ $operation =~ init|lidar|imu ]]; then
    host=$( load_config $( config_path_concat $options_config device/target ) )
    [[ $host ]] || die "target host name or ip address is required"
    [[ $host =~ ^[0-9.]+$ ]] && host_ip=$host || host_ip=$( getent hosts $host | awk '{ print $1 }' )
    [[ $host_ip ]] || die "unable to resolve $host"
fi

# send stdout to stderr
function log_stdout()
{
    sed "s/^/$scriptname: /" >&2
}

function run_cmd()
{
    [[ $1 == -q ]] && shift || verbose $1
    echo $1 | socat tcp:$lidar:$command_port -
}

function ping_lidar()
{
    ping -c1 -W1 $lidar >/dev/null || die "$lidar is not reachable, check \"sudo journalctl -u dnsmasq.service\""
}

function send_commands()
{
    ping_lidar
    while read line; do
        run_cmd "$line"
    done
}

function get_parameter()
{
    local name=$1
    local result=
    local retries=0
    while (( retries < 5 )); do
        result=$( run_cmd "get_config_param active $name" )
        [[ $result ]] && break
        say "couldn't read $name, retrying..."
        (( retries++ ))
        sleep 1
    done
    [[ $result ]] || say "failed to read $name"
    echo $result | csv-quote --unquote
}

function set_parameter()
{
    local name=$1
    local value=$2
    local response=$( run_cmd "set_config_param $name $value" )
    [[ $response == "set_config_param" ]] || { say "failed to set $name to $value"; die "$response"; }
}

function wrap_json_arrays()
{
    gawk '
        /\[$/    { in_array=1; i=0; print; next }
        /\],?$/  { in_array=0 }
        in_array { i++; if(i%4==1) printf $0; else if( i%4 == 0 ) print " "$1; else printf " "$1; next }
                 { print }
        '
}

function version_ge()
{
    local value=$1
    local compare_to=$2
    echo -e "${compare_to}\n${value}" | sort -V | sed -n 2p | grep -q "^${value}$"
}

function output_config()
{
    ping_lidar
    {
        for operation in lidar imu; do
            echo "$operation/address=$( load_config $( config_path_concat $options_config $operation/address ) 2>/dev/null )"
            echo "$operation/port=$( load_config $( config_path_concat $options_config $operation/port ) 2>/dev/null )"
            echo "$operation/binary=$( output_format $operation )"
            local bandwidth_monitor_config=$( load_config $( config_path_concat $options_config $operation/bandwidth_monitor ) 2> /dev/null )
            if [[ $bandwidth_monitor_config ]]; then
                echo "$bandwidth_monitor_config" | sed "s#^#lidar/bandwidth_monitor/#"
                echo
            fi
        done
        local firmware=$( run_cmd get_sensor_info | name-value-get build_rev | sed 's/^v//' )
        echo "device/host=$lidar"
        echo "device/target=$( load_config $( config_path_concat $options_config device/target ) 2>/dev/null )"
        echo "device/firmware=$firmware"
        run_cmd "get_config_txt" | name-value-convert | sed 's#^#parameters/#'
        run_cmd "get_beam_intrinsics" | name-value-convert | sed 's#^#beam_intrinsics/#'
        run_cmd "get_imu_intrinsics" | name-value-convert | sed 's#^#imu_intrinsics/#'
        run_cmd "get_lidar_intrinsics" | name-value-convert | sed 's#^#lidar_intrinsics/#'
        version_ge $firmware 2.0.0 && run_cmd "get_lidar_data_format" | name-value-convert | sed 's#^#lidar_data_format/#'
    } | name-value-convert --to json | wrap_json_arrays
}

function reinitialize()
{
    verbose "reinitializing..."
    verbose "status=$( run_cmd get_sensor_info | name-value-get status )"
    run_cmd "reinitialize"
    local status=$( run_cmd get_sensor_info | name-value-get status )
    while [[ $status != "RUNNING" ]]; do
        verbose "status=$status"
        sleep 1
        status=$( run_cmd -q get_sensor_info | name-value-get status 2> /dev/null )
    done
    verbose "status=$status"
}

function update_parameter()
{
    local name=$1
    local value=$2
    [[ $value ]] || return

    local current_value=$( get_parameter $name )
    if [[ $current_value != $value ]]; then
        say "setting $name to $value (was $current_value)"
        set_parameter $name $value
    fi
}

function initialize()
{
    verbose "initializing from $options_config..."
    ping_lidar

    local parameter parameter_var_name
    # sort the parameters so they always get set in the same order
    for parameter in $( tr " " "\n" <<< ${!configurable_parameters[@]} | sort ); do
        parameter_var_name=parameter_$parameter
        update_parameter $parameter ${!parameter_var_name}
    done

    verbose "status=$( run_cmd get_sensor_info | name-value-get status )"
    udp_port_lidar=$( get_parameter udp_port_lidar )
    udp_port_imu=$( get_parameter udp_port_imu )
    verbose "lidar port=$udp_port_lidar"
    verbose "imu port=$udp_port_imu"
    set_parameter udp_ip $host_ip
    reinitialize                    # to set the udp_ip
}

function alerts()
{
    local input_fields="cursor,code,realtime,brief,description"
    local output_fields=$( output_fields alerts ),next_cursor
    local eval_format=$( output_format alerts | csv-fields rename --fields t --to ul ),ul

    verbose "alerts..."
    run_cmd get_alerts \
        | name-value-convert \
        | name-value-to-csv --fields $input_fields --prefix alerts --unindexed-fields=next_cursor \
        | csv-quote --unquote | csv-quote \
        | csv-shuffle --fields $input_fields,next_cursor \
                      --output $( csv-fields rename --fields t --to realtime <<< $output_fields ) \
        | csv-eval --fields $output_fields --format $eval_format "t=t/1000000000" \
        | csv-time --fields $( csv-fields clear --except t <<< $output_fields ) --from seconds --to iso
}

next_cursor=0

function stream_alerts()
{
    local fields=$( output_fields alerts ),next_cursor
    local format=$( output_format alerts ),ul

    verbose "streaming alerts..."
    while : ; do
        local alerts=$( alerts )
        local new_next_cursor=$( echo "$alerts" | head -1 | csv-shuffle --fields $fields --output next_cursor )
        verbose "new_next_cursor=$new_next_cursor"
        if (( new_next_cursor != next_cursor )); then
            echo "$alerts" | csv-select --fields $fields --format $format "cursor;from=$next_cursor"
            next_cursor=$new_next_cursor
        fi
        sleep 5
    done
}

function output_alerts()
{
    local output_fields=$( output_fields alerts )
    csv-shuffle --fields $output_fields,next_cursor --output $output_fields
}

function publish_bandwidth_stats()
{
    local port=$1
    io-bandwidth 2> >( io-publish tcp:$port )
}

# we need to convert the host time to 64 bit unsigned integer of nanoseconds from epoch
#
# TODO: replace with option to udp-client or csv-time-stamp to directly drop in
# the nanosecond timestamp in the right place in the data
function use_host_time()
{
    [[ $operation == "lidar" ]] || die "--use-host-time only supported for lidar data"
    local fields=$( output_fields lidar )
    local format=$( output_format lidar )
    # prepend with host time
    # replace device time with host time
    # change host time from microseconds to nanoseconds from epoch, to match device data format
    csv-time-stamp --binary $format \
        | csv-shuffle --fields host_time,$fields --binary t,$format \
                      --output $( echo $fields | tr , '\n' | sed 's/^timestamp$/host_time/' | paste -s -d, ) \
        | csv-eval --fields $fields --binary $format "timestamp=timestamp*1000"
}

function stream()
{
    verbose "streaming..."
    ping_lidar

    local firmware=$( run_cmd -q get_sensor_info | name-value-get build_rev 2> /dev/null )
    [[ $firmware =~ $tested_firmware_re ]] || { say "warning: verified against firmware versions $tested_firmware"; say "         this device is $firmware"; }

    local active_udp_ip=$( get_parameter udp_ip )
    if [[ $active_udp_ip != $host_ip ]]; then
        verbose "active udp_ip=$active_udp_ip, should be $host_ip"
        initialize | log_stdout
    fi

    local port=$( get_parameter $1 )
    local packet_size=$( packet_size $operation )
    verbose "streaming $packet_size byte packets from port $port"

    local bandwidth_monitor_port=$( load_config $( config_path_concat $options_config $operation/bandwidth_monitor/port ) )
    local bandwidth_fn=cat
    if [[ $bandwidth_monitor_port ]]; then
        bandwidth_fn="publish_bandwidth_stats $bandwidth_monitor_port"
        verbose "sending bandwidth data to port $bandwidth_monitor_port"
    fi

    local timestamp_fn=cat
    (( options_use_host_time )) && timestamp_fn=use_host_time

    udp-client $port | $bandwidth_fn | $timestamp_fn
}

case $operation in
    command)        send_commands ;;
    config)         output_config ;;
    init)           initialize ;;
    lidar)          stream udp_port_lidar ;;
    imu)            stream udp_port_imu ;;
    alerts)         alerts | output_alerts ;;
    stream_alerts)  stream_alerts | output_alerts ;;
    *)              die "requires operation"
esac
