#!/bin/bash

read params
image-pinhole distortion-map --verbose --config=config.json > output/map.bin
result=$?
(( result == 0 )) || { echo "$0: image-pinhole exited non-zero status: $result"; exit 1; }
cat output/map.bin \
    | csv-from-bin f \
    | csv-paste 'line-number;size=4' 'line-number;size=4;index' - \
    | sed -e 's#^\([0-9]\),#output/y[\1]=#' -e 's#=\([0-9]\),#/x[\1]=#'



#cat -n output/out | sed 's#^ *#output[#;s#\t#]="#;s#$#"#'
